package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"strconv"
	"strings"
)

type SalahTimeRecord struct {
	Month     int         `json:"month"`
	Year      int         `json:"year"`
	Salatimes []Salatimes `json:"salatimes"`
}
type SalahTime struct {
	Hour int `json:"hour"`
	Min  int `json:"min"`
}
type Salatimes struct {
	Fajar18   SalahTime `json:"fajar18"`
	Fajar15   SalahTime `json:"fajar15"`
	Sunrise   SalahTime `json:"sunrise"`
	Ishraq    SalahTime `json:"ishraq"`
	Chasht    SalahTime `json:"chasht"`
	Zawal     SalahTime `json:"zawal"`
	Zuhar     SalahTime `json:"zuhar"`
	AsrShafai SalahTime `json:"asarshafai"`
	AsrHanfi  SalahTime `json:"asrhanfi"`
	Maghrib   SalahTime `json:"maghrib"`
	Isha15    SalahTime `json:"isha15"`
	Isha18    SalahTime `json:"isha18"`
}

func convertStrToSalaTime(str string) SalahTime {
	parts := strings.Split(strings.Split(str, " ")[0], ":")
	h , _ := strconv.Atoi(parts[0])
	m , _ := strconv.Atoi(parts[1])
	return SalahTime{ Hour: h, Min: m}
}

func main() {
	resp1, err := http.Get("http://api.aladhan.com/v1/calendarByCity?city=Buffalo&country=USA&state=NY&school=0&method=99&methodSettings=15,null,15&month=08&year=2020")
	resp2, err := http.Get("http://api.aladhan.com/v1/calendarByCity?city=Buffalo&country=USA&state=NY&school=1&method=99&methodSettings=18,null,18&month=08&year=2020")

	if err != nil {
		log.Fatalln(err)
	}

	var d1 AutoGenerated
	json.NewDecoder(resp1.Body).Decode(&d1)

	var d2 AutoGenerated
	json.NewDecoder(resp2.Body).Decode(&d2)

	//fmt.Printf("%+v", decoded)

	if d1.Code == 200 && d2.Code == 200 {
		for i, _ := range d1.Data {
			//fmt.Printf("%v:%v\n", v.Date.Gregorian.Month.Number,  v.Date.Gregorian.Day)
			var times Salatimes
			times.Fajar15 = convertStrToSalaTime(d1.Data[i].Timings.Fajr)
			times.Fajar18 = convertStrToSalaTime(d2.Data[i].Timings.Fajr)

			times.Sunrise = convertStrToSalaTime(d1.Data[i].Timings.Sunrise)

			times.Zuhar = convertStrToSalaTime(d1.Data[i].Timings.Dhuhr)

			times.AsrShafai = convertStrToSalaTime(d1.Data[i].Timings.Asr)
			times.AsrHanfi = convertStrToSalaTime(d2.Data[i].Timings.Asr)

			times.Maghrib = convertStrToSalaTime(d1.Data[i].Timings.Sunset)

			times.Isha15 = convertStrToSalaTime(d1.Data[i].Timings.Isha)
			times.Isha18 = convertStrToSalaTime(d2.Data[i].Timings.Isha)

			fmt.Printf("%v %+v\n", d1.Data[i].Date.Gregorian.Day, times)
			//fmt.Printf("index: %v, day %v/%v, Fajar15 %v\t Fajar 18 %v\n", i, d1.Data[i].Date.Gregorian.Day, d2.Data[i].Date.Gregorian.Day, convertStrToSalaTime(d1.Data[i].Timings.Fajr), convertStrToSalaTime(d2.Data[i].Timings.Fajr));

		}
	}

}

type AutoGenerated struct {
	Code   int    `json:"code"`
	Status string `json:"status"`
	Data   []Data `json:"data"`
}
type Timings struct {
	Fajr     string `json:"Fajr"`
	Sunrise  string `json:"Sunrise"`
	Dhuhr    string `json:"Dhuhr"`
	Asr      string `json:"Asr"`
	Sunset   string `json:"Sunset"`
	Maghrib  string `json:"Maghrib"`
	Isha     string `json:"Isha"`
	Imsak    string `json:"Imsak"`
	Midnight string `json:"Midnight"`
}
type Weekday struct {
	En string `json:"en"`
}
type Month struct {
	Number int    `json:"number"`
	En     string `json:"en"`
}

//type Designation struct {
//	Abbreviated string `json:"abbreviated"`
//	Expanded    string `json:"expanded"`
//}
type Gregorian struct {
	Date        string      `json:"date"`
	Format      string      `json:"format"`
	Day         string      `json:"day"`
	Weekday     Weekday     `json:"weekday"`
	Month       Month       `json:"month"`
	Year        string      `json:"year"`
	//Designation Designation `json:"designation"`
}
//type Weekday struct {
//	En string `json:"en"`
//	Ar string `json:"ar"`
//}
//type Month struct {
//	Number int    `json:"number"`
//	En     string `json:"en"`
//	Ar     string `json:"ar"`
//}
//type Hijri struct {
//	Date        string      `json:"date"`
//	Format      string      `json:"format"`
//	Day         string      `json:"day"`
//	Weekday     Weekday     `json:"weekday"`
//	Month       Month       `json:"month"`
//	Year        string      `json:"year"`
//	Designation Designation `json:"designation"`
//	Holidays    []string    `json:"holidays"`
//}
type Date struct {
	Readable  string    `json:"readable"`
	Timestamp string    `json:"timestamp"`
	Gregorian Gregorian `json:"gregorian"`
	//Hijri     Hijri     `json:"hijri"`
}
type Params struct {
	Fajr int `json:"Fajr"`
	Isha int `json:"Isha"`
}
type Method struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	Params Params `json:"params"`
}
type Offset struct {
	Imsak    int `json:"Imsak"`
	Fajr     int `json:"Fajr"`
	Sunrise  int `json:"Sunrise"`
	Dhuhr    int `json:"Dhuhr"`
	Asr      int `json:"Asr"`
	Maghrib  int `json:"Maghrib"`
	Sunset   int `json:"Sunset"`
	Isha     int `json:"Isha"`
	Midnight int `json:"Midnight"`
}
type Meta struct {
	Latitude                 float64 `json:"latitude"`
	Longitude                float64 `json:"longitude"`
	Timezone                 string  `json:"timezone"`
	Method                   Method  `json:"method"`
	LatitudeAdjustmentMethod string  `json:"latitudeAdjustmentMethod"`
	MidnightMode             string  `json:"midnightMode"`
	School                   string  `json:"school"`
	Offset                   Offset  `json:"offset"`
}
type Data struct {
	Timings Timings `json:"timings"`
	Date    Date    `json:"date"`
	Meta Meta `json:"meta"`
}
